-------------------------------------------------------------------------------
-- Premade Regions
-------------------------------------------------------------------------------
-- Copyright (c) 2019 Bernhard Saumweber (gihub.com/0xbs)
--                and github.com/Rustyb0y
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
-------------------------------------------------------------------------------

local PR = select(2, ...)

PR.REGION_TEXT = {
    ["syd"] = "Sydney",
    ["la"] = "Los Angeles",
    ["chi"] = "Chicago",
    ["mex"] = "Mexico",
    ["bzl"] = "Brazil",
}

PR.DUNGEON_TEXT = {
    ["Temple of Sethraliss"] = "Temple",
    ["Waycrest Manor"] = "Waycrest",
    ["Kings' Rest"] = "Kings' Rest",
    ["Freehold"] = "Freehold",
    ["Shrine of the Storm"] = "Shrine",
    ["Tol Dagor"] = "Tol'Dagor",
    ["Mechagon Junkyard"] = "Junkyard",
    ["Mechagon Workshop"] = "Workshop",
    ["The Underrot"] = "Underrot",
    ["Atal'Dazar"] = "Atal'Dazar",
    ["Siege of Boralus"] = "Siege",
    ["THE MOTHERLODE"] = "Motherlode",
}

PR.REGION_TEXT_META = {}
PR.REGION_TEXT_META.__index = function (table, key) return "Unknown" end
setmetatable(PR.REGION_TEXT, PR.REGION_TEXT_META)

PR.REGION_COLORED = {
    ["syd"] = "|cFF009900AUS|r",
    ["la"] = "|cFF3399FFLA|r",
    ["chi"] = "|cFFFF0000CHI|r",
    ["mex"] = "|cFF006600M|cFFFFFFFFE|cFFCC3300X|r",
    ["bzl"] = "|cFF006600B|cFFFFFF00Z|cFF3333CCL|r",
}

PR.REGION_COLORED_META = {}
PR.REGION_COLORED_META.__index = function (table, key) return "|cFFFFFFFF[?]|r " end
setmetatable(PR.REGION_COLORED, PR.REGION_COLORED_META)

PR.REGION_REALMS = {
    ["syd"] = {
        "Aman'Thul",
        "Barthilas",
        "Caelestrasz",
        "Dath'Remar",
        "Dreadmaul",
        "Frostmourne",
        "Gundrak",
        "Jubei'Thos",
        "Khaz'goroth",
        "Nagrand",
        "Saurfang",
        "Thaurissan",
    },
    ["la"] = {
        "Aegwynn",
        "Anub'arak",
        "Bladefist",
        "Bonechewer",
        "Chromaggus",
        "Crushridge",
        "Daggerspine",
        "Eitrigg",
        "Frostmane",
        "Garithos",
        "Gurubashi",
        "Hakkar",
        "Korgath",
        "Kul Tiras",
        "Misha",
        "Moon Guard",
        "Muradin",
        "Nathrezim",
        "Nazgrel",
        "Nesingwary",
        "Nordrassil",
        "Quel'dorei",
        "Rexxar",
        "Runetotem",
        "Sen'jin",
        "Shu'halo",
        "Smolderthorn",
        "Tortheldrin",
        "Uther",
        "Vek'nilash",
        "Drak'Tharon",
        "Eldre'Thalas",
        "Firetree",
        "Garrosh",
        "Korialstrasz",
        "Malorne",
        "Rivendare",
        "Azjol-Nerub",
        "AzjolNerub",
        "Blackwater Raiders",
        "Bloodscalp",
        "Boulderfist",
        "Cairne",
        "Darkspear",
        "Dunemaul",
        "Hydraxis",
        "Khaz Modan",
        "Maiev",
        "Perenolde",
        "Shadow Council",
        "Stonemaul",
        "Terenas",
        "Akama",
        "Antonidas",
        "Arathor",
        "Blackrock",
        "Borean Tundra",
        "Bronzebeard",
        "Cenarion Circle",
        "Cenarius",
        "Darrowmere",
        "Draenor",
        "Dragonblight",
        "Dragonmaw",
        "Drak'thul",
        "Draka",
        "Drenden",
        "Echo Isles",
        "Farstriders",
        "Feathermoon",
        "Fenris",
        "Frostwolf",
        "Hyjal",
        "Kil'jaeden",
        "Kilrogg",
        "Lightbringer",
        "Mok'Nathal",
        "Mug'thol",
        "Ner'zhul",
        "Proudmoore",
        "Scarlet Crusade",
        "Shadowsong",
        "Shandris",
        "Silver Hand",
        "Silvermoon",
        "Sisters of Elune",
        "Skywall",
        "Spirestone",
        "Stormscale",
        "Suramar",
        "Thorium Brotherhood",
        "Tichondrius",
        "Uldum",
        "Vashj",
        "Windrunner",
        "Winterhoof",
        "Wyrmrest Accord",
    },
    ["chi"] = {
        "Agamaggan",
        "Aggramar",
        "Alexstrasza",
        "Alleria",
        "Anvilmar",
        "Archimonde",
        "Auchindoun",
        "Azgalor",
        "Azshara",
        "Azuremyst",
        "Blackhand",
        "Blackwing Lair",
        "Blade's Edge",
        "Burning Legion",
        "Cho'gall",
        "Dawnbringer",
        "Dentarg",
        "Destromath",
        "Dethecus",
        "Detheroc",
        "Emerald Dream",
        "Fizzcrank",
        "Galakrond",
        "Garona",
        "Ghostlands",
        "Gorefiend",
        "Greymane",
        "Haomarush",
        "Hellscream",
        "Icecrown",
        "Illidan",
        "Jaedenar",
        "Kael'thas",
        "Khadgar",
        "Kirin Tor",
        "Laughing Skull",
        "Lethon",
        "Lightninghoof",
        "Madoran",
        "Maelstrom",
        "Mal'Ganis",
        "Malygos",
        "Ravencrest",
        "Ravenholdt",
        "Sargeras",
        "Sentinels",
        "Shadowmoon",
        "Spinebreaker",
        "Staghelm",
        "Steamwheedle Cartel",
        "Stormreaver",
        "Tanaris",
        "Terokkar",
        "The Underbog",
        "The Venture Co",
        "Thunderhorn",
        "Thunderlord",
        "Twisting Nether",
        "Uldaman",
        "Undermine",
        "Whisperwind",
        "Wildhammer",
        "Zangarmarsh",
        "Altar of Storms",
        "Alterac Mountains",
        "Anetheron",
        "Area 52",
        "Argent Dawn",
        "Arthas",
        "Arygos",
        "Balnazzar",
        "Black Dragonflight",
        "Bleeding Hollow",
        "Blood Furnace",
        "Bloodhoof",
        "Burning Blade",
        "Dalaran",
        "Durotan",
        "Duskwood",
        "Earthen Ring",
        "Elune",
        "Eonar",
        "Eredar",
        "Exodar",
        "Gilneas",
        "Gorgonnash",
        "Grizzly Hills",
        "Gul'dan",
        "Kargath",
        "Lightning's Blade",
        "Llane",
        "Lothar",
        "Magtheridon",
        "Malfurion",
        "Mannoroth",
        "Medivh",
        "Nazjatar",
        "Norgannon",
        "Skullcrusher",
        "Stormrage",
        "The Forgotten Coast",
        "The Scryers",
        "Thrall",
        "Trollbane",
        "Turalyon",
        "Velen",
        "Warsong",
        "Ysera",
        "Ysondre",
        "Zul'jin",
        "Deathwing",
        "Kel'Thuzad",
        "Aerie Peak",
        "Andorhal",
        "Baelgun",
        "Coilfang",
        "Dalvengyr",
        "Dark Iron",
        "Demon Soul",
        "Doomhammer",
        "Executus",
        "Gnomeregan",
        "Kalecgos",
        "Moonrunner",
        "Onyxia",
        "Scilla",
        "Shattered Halls",
        "Shattered Hand",
        "Ursin",
        "Zuluhed",
    },
    ["mex"] = {
        "Drakkari",
        "Quel'Thalas",
        "Ragnaros",
    },
    ["bzl"] = {
        "Azralon",
        "Gallywix",
        "Goldrinn",
        "Nemesis",
        "Tol Barad",
    }
}