-------------------------------------------------------------------------------
-- Premade Regions
-------------------------------------------------------------------------------
-- Copyright (c) 2019 Bernhard Saumweber (gihub.com/0xbs)
--                and github.com/Rustyb0y
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
-------------------------------------------------------------------------------

local PR = select(2, ...)

PR.REGION_TEXT = {
    ["eng"] = "English",
    ["ger"] = "German",
    ["fra"] = "French",
    ["spa"] = "Spainish",
    ["rus"] = "Russian",
    ["oce"] = "Oceanic",
    ["la"] = "Los Angeles",
    ["chi"] = "Chicago",
    ["mex"] = "Mexican",
    ["bzl"] = "Brazil",
}
PR.REGION_TEXT_META = {}
PR.REGION_TEXT_META.__index = function (table, key) return "Unknown" end
setmetatable(PR.REGION_TEXT, PR.REGION_TEXT_META)

PR.REGION_COLORED = {
    ["eng"] = "|cFFFFFFFFENG|r",
    ["ger"] = "|cFFDA291CGER|r",
    ["fra"] = "|cFFDA291CFRA|r",
    ["spa"] = "|cFFDA291CSPA|r",
    ["rus"] = "|cFFDA291CRUS|r",
    ["oce"] = "|cFF009900OCE|r",
    ["la"] = "|cFF3399FFLA|r",
    ["chi"] = "|cFFFF0000CHI|r",
    ["mex"] = "|cFF006600M|r|cFFFFFFFFE|r|cFFCC3300X|r",
    ["bzl"] = "|cFF006600B|r|cFFFFFF00Z|r|cFF3333CCL|r",
}
PR.REGION_COLORED_META = {}
PR.REGION_COLORED_META.__index = function (table, key) return "|cFFFFFFFF?|r " end
setmetatable(PR.REGION_COLORED, PR.REGION_COLORED_META)

PR.EU_REGION_REALMS = {
    ["eng"] = {
        "Aerie Peak",
        "Agamaggan",
        "Aggramar",
        "Ahn'Qiraj",
        "Al'Akir",
        "Alonsus",
        "Anachronos",
        "Arathor",
        "Argent Dawn",
        "Aszune",
        "Auchindoun",
        "Azjol-Nerub",
        "Azuremyst",
        "Balnazzar",
        "Blade's Edge",
        "Bladefist",
        "Bloodfeather",
        "Bloodhoof",
        "Bloodscalp",
        "Boulderfist",
        "Bronze Dragonflight",
        "Bronzebeard",
        "Burning Blade",
        "Burning Legion",
        "Burning Steppes",
        "Chamber of Aspects",
        "Chromaggus",
        "Chrushridge",
        "Daggerspine",
        "Darkmoon Faire",
        "Darksorrow",
        "Darkspear",
        "Deathwing",
        "Defias Brotherhood",
        "Dentarg",
        "Doomhammer",
        "Draenor",
        "Dragonblight",
        "Dragonmaw",
        "Drak'thul",
        "Dunemaul",
        "Earthen Ring",
        "Emerald Dream",
        "Emeriss",
        "Eonar",
        "Executus",
        "Frostmane",
        "Frostwhisper",
        "Genjuros",
        "Ghostlands",
        "Grim Batol",
        "Hakkar",
        "Haomarush",
        "Hellfire",
        "Hellscream",
        "Jaedenar",
        "Karazhan",
        "Kazzak",
        "Khadgar",
        "Kilrogg",
        "Kor'gall",
        "Kul Tiras",
        "Laughing Skull",
        "Lightbringer",
        "Lightning's Blade",
        "Magtheridon",
        "Mazrigos",
        "Moonglade",
        "Nagrand",
        "Neptulon",
        "Nordrassil",
        "Outland",
        "Quel'Thalas",
        "Ragnaros",
        "Ravencrest",
        "Ravenholt",
        "Runetotem",
        "Saurfang",
        "Scarshield Legion",
        "Shadowsong",
        "Shattered Halls",
        "Shattered Hand",
        "Silvermoon",
        "Skullcrusher",
        "Spinebreaker",
        "Sporeggar",
        "Steamwheedle Cartel",
        "Stormrage",
        "Stormreaver",
        "Stormscale",
        "Sunstrider",
        "Sylvanas",
        "Talnivarr",
        "Tarren Mill",
        "Terenas",
        "Terokkar",
        "The Maelstrom",
        "The Sha'tar",
        "The Venture Co",
        "Thunderhorn",
        "Trollbane",
        "Turalyon",
        "Twilight's Hammer",
        "Twisting Nether",
        "Vashj",
        "Vek'nilash",
        "Wildhammer",
        "Xavius",
        "Zenedar"
    },
    ["ger"] = {
        "Aegwynn",
        "Alexstrasza",
        "Alleria",
        "Aman'thul",
        "Ambossar",
        "Anetheron",
        "Antonidas",
        "Anub'arak",
        "Area 52",
        "Arthas",
        "Arygos",
        "Azshara",
        "Baelgun",
        "Blackhand",
        "Blackmoore",
        "Blackrock",
        "Blutkessel",
        "Dalvengyr",
        "Das Konsortium",
        "Das Syndikat",
        "Der Abyssische Rat",
        "Der Mithrilorden",
        "Der Rat von Dalaran",
        "Destromath",
        "Dethecus",
        "Die Aldor",
        "Die Arguswacht",
        "Die ewige Wacht",
        "Die Nachtwache",
        "Die Silverne Hand",
        "Die Todenskrallen",
        "Dun Morogh",
        "Durotan",
        "Echsenkessel",
        "Eredar",
        "Festung der Stürme",
        "Forscherliga",
        "Frostmourne",
        "Frostwolf",
        "Garrosh",
        "Gilneas",
        "Gorgonnash",
        "Gul'dan",
        "Kargath",
        "Kel'Thuzad",
        "Khaz'goroth",
        "Kil'jaeden",
        "Krag'jin",
        "Kult der Verdammten",
        "Lordaeron",
        "Lothar",
        "Madmortem",
        "Mal'Ganis",
        "Malfurion",
        "Malorne",
        "Malygos",
        "Mannoroth",
        "Mug'thol",
        "Nathrezim",
        "Nazjatar",
        "Nefarian",
        "Nera'thor",
        "Nethersturm",
        "Norgannon",
        "Nozdormu",
        "Onyxia",
        "Perenolde",
        "Proudmoore",
        "Rajaxx",
        "Rexxar",
        "Sen'jin",
        "Shattrath",
        "Taerar",
        "Teldrassil",
        "Terrordar",
        "Theradras",
        "Thrall",
        "Tichondrius",
        "Tirion",
        "Todeswache",
        "Ulduar",
        "Un'Goro",
        "Vek'lor",
        "Wrathbringer",
        "Ysera",
        "Zirkel des Cenarius",
        "Zuluhed"
    },
    ["fra"] = {
        "Arak-arahm",
        "Arathi",
        "Archimonde",
        "Chants éternels",
        "Cho'gall",
        "Confrérie du Thorium",
        "Conseil des Ombres",
        "Culte de la Rive noire",
        "Dalaran",
        "Drek'Thar",
        "Eitrigg",
        "Eldre'Thalas",
        "Elune",
        "Garona",
        "Hyjal",
        "Illidan",
        "Kael'thas",
        "Khaz Modan",
        "Kirin Tor",
        "Krasus",
        "La Croisade écarlate",
        "Les Clairvoyants",
        "Les Sentinelles",
        "Marécage de Zangar",
        "Medivh",
        "Naxxramas",
        "Ner'zhul",
        "Rashgarroth",
        "Sargeras",
        "Sinstralis",
        "Suramar",
        "Temple noir",
        "Throk'Feroth",
        "Uldaman",
        "Varimathras",
        "Vol'Jin",
        "Ysondre"
    },
    ["spa"] = {
        "Aggra(Português)",
        "Colinas Pardas",
        "C'Thun",
        "Dun Modr",
        "Exodar",
        "Los Errantes",
        "Minahonda",
        "Sanguino",
        "Shen'dralar",
        "Tyrande",
        "Uldum",
        "Zul'jin"
    },
    ["rus"] = {
        "Азурегос",
        "Борейская тундра",
        "Вечная Песня",
        "Галакронд",
        "Голдринн",
        "Гордунни",
        "Гром",
        "Дракономор",
        "Король-лич",
        "Пиратская Бухта",
        "Подземье",
        "Разувий",
        "Ревущий фьорд",
        "Свежеватель Душ",
        "Седогрив",
        "Страж смерти",
        "Термоштепсель",
        "Ткач Смерти",
        "Черныйшрам",
        "Ясеневый лес"
    },
    ["ita"] = {
        "Nemesis",
        "Pozzo dell'Eternità"
    }
}

PR.US_REGION_REALMS = {
    ["oce"] = {
        "Aman'Thul",
        "Barthilas",
        "Caelestrasz",
        "Dath'Remar",
        "Dreadmaul",
        "Frostmourne",
        "Gundrak",
        "Jubei'Thos",
        "Khaz'goroth",
        "Nagrand",
        "Saurfang",
        "Thaurissan",
    },
    ["la"] = {
        "Aegwynn",
        "Akama",
        "Antonidas",
        "Anub'arak",
        "Arathor",
        "Azjol-Nerub",
        "Azjolnerub",
        "Blackrock",
        "Blackwater Raiders",
        "Bladefist",
        "Bloodscalp",
        "Bonechewer",
        "Borean Tundra",
        "Boulderfist",
        "Bronzebeard",
        "Cairne",
        "Cenarion Circle",
        "Cenarius",
        "Chromaggus",
        "Crushridge",
        "Daggerspine",
        "Darkspear",
        "Darrowmere",
        "Draenor",
        "Dragonblight",
        "Dragonmaw",
        "Drak'Tharon",
        "Drak'thul",
        "Draka",
        "Drenden",
        "Dunemaul",
        "Echo Isles",
        "Eitrigg",
        "Eldre'Thalas",
        "Farstriders",
        "Feathermoon",
        "Fenris",
        "Firetree",
        "Frostmane",
        "Frostwolf",
        "Garithos",
        "Garrosh",
        "Gurubashi",
        "Hakkar",
        "Hydraxis",
        "Hyjal",
        "Khaz Modan",
        "Kil'jaeden",
        "Kilrogg",
        "Korgath",
        "Korialstrasz",
        "Kul Tiras",
        "Lightbringer",
        "Maiev",
        "Malorne",
        "Misha",
        "Mok'Nathal",
        "Moon Guard",
        "Mug'thol",
        "Muradin",
        "Nathrezim",
        "Nazgrel",
        "Ner'zhul",
        "Nesingwary",
        "Nordrassil",
        "Perenolde",
        "Proudmoore",
        "Quel'dorei",
        "Rexxar",
        "Rivendare",
        "Runetotem",
        "Scarlet Crusade",
        "Sen'jin",
        "Shadow Council",
        "Shadowsong",
        "Shandris",
        "Shu'halo",
        "Silver Hand",
        "Silvermoon",
        "Sisters of Elune",
        "Skywall",
        "Smolderthorn",
        "Spirestone",
        "Stonemaul",
        "Stormscale",
        "Suramar",
        "Terenas",
        "Thorium Brotherhood",
        "Tichondrius",
        "Tortheldrin",
        "Uldum",
        "Uther",
        "Vashj",
        "Vek'nilash",
        "Windrunner",
        "Winterhoof",
        "Wyrmrest Accord",
    },
    ["chi"] = {
        "Aerie Peak",
        "Agamaggan",
        "Aggramar",
        "Alexstrasza",
        "Alleria",
        "Altar of Storms",
        "Alterac Mountains",
        "Andorhal",
        "Anetheron",
        "Anvilmar",
        "Archimonde",
        "Area 52",
        "Argent Dawn",
        "Arthas",
        "Arygos",
        "Auchindoun",
        "Azgalor",
        "Azshara",
        "Azuremyst",
        "Baelgun",
        "Balnazzar",
        "Black Dragonflight",
        "Blackhand",
        "Blackwing Lair",
        "Blade's Edge",
        "Bleeding Hollow",
        "Blood Furnace",
        "Bloodhoof",
        "Burning Blade",
        "Burning Legion",
        "Cho'gall",
        "Coilfang",
        "Dalaran",
        "Dalvengyr",
        "Dark Iron",
        "Dawnbringer",
        "Deathwing",
        "Demon Soul",
        "Dentarg",
        "Destromath",
        "Dethecus",
        "Detheroc",
        "Doomhammer",
        "Durotan",
        "Duskwood",
        "Earthen Ring",
        "Elune",
        "Emerald Dream",
        "Eonar",
        "Eredar",
        "Executus",
        "Exodar",
        "Fizzcrank",
        "Galakrond",
        "Garona",
        "Ghostlands",
        "Gilneas",
        "Gnomeregan",
        "Gorefiend",
        "Gorgonnash",
        "Greymane",
        "Grizzly Hills",
        "Gul'dan",
        "Haomarush",
        "Hellscream",
        "Icecrown",
        "Illidan",
        "Jaedenar",
        "Kael'thas",
        "Kalecgos",
        "Kargath",
        "Kel'Thuzad",
        "Khadgar",
        "Kirin Tor",
        "Laughing Skull",
        "Lethon",
        "Lightning's Blade",
        "Lightninghoof",
        "Llane",
        "Lothar",
        "Madoran",
        "Maelstrom",
        "Magtheridon",
        "Mal'Ganis",
        "Malfurion",
        "Malygos",
        "Mannoroth",
        "Medivh",
        "Moonrunner",
        "Nazjatar",
        "Norgannon",
        "Onyxia",
        "Ravencrest",
        "Ravenholdt",
        "Sargeras",
        "Scilla",
        "Sentinels",
        "Shadowmoon",
        "Shattered Halls",
        "Shattered Hand",
        "Skullcrusher",
        "Spinebreaker",
        "Staghelm",
        "Steamwheedle Cartel",
        "Stormrage",
        "Stormreaver",
        "Tanaris",
        "Terokkar",
        "The Forgotten Coast",
        "The Scryers",
        "The Underbog",
        "The Venture Co",
        "Thrall",
        "Thunderhorn",
        "Thunderlord",
        "Trollbane",
        "Turalyon",
        "Twisting Nether",
        "Uldaman",
        "Undermine",
        "Ursin",
        "Velen",
        "Warsong",
        "Whisperwind",
        "Wildhammer",
        "Ysera",
        "Ysondre",
        "Zangarmarsh",
        "Zul'jin",
        "Zuluhed",
    },
    ["mex"] = {
        "Drakkari",
        "Quel'Thalas",
        "Ragnaros",
    },
    ["bzl"] = {
        "Azralon",
        "Gallywix",
        "Goldrinn",
        "Nemesis",
        "Tol Barad",
    }
}
